# Generated by Django 5.2.1 on 2025-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_meal_stock_alter_meal_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/default_meal.jpg', upload_to='meal_images'),
        ),
    ]
