# Generated by Django 5.2.1 on 2025-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/default_meal1.jpg', upload_to='meal_images'),
        ),
    ]
