# Generated by Django 5.2.1 on 2025-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/default_meal.jpg', upload_to='meal_images'),
        ),
    ]
